#!/usr/bin/env bash

HEAD1="<!DOCTYPE html>
<html><head>
<meta charset=\"utf-8\">
<script>
document.addEventListener('play', function(e){
  var audios = document.getElementsByTagName('audio');
  for(var i = 0, len = audios.length; i < len;i++){
    if(audios[i] == e.target) continue;
    audios[i].pause();
    audios[i].currentTime = 0;
  }
}, true);
var elem = document.documentElement;
var fullscreen = false;
function toggleFullScreen() {
  if (fullscreen) {
    if (document.exitFullscreen) {
      document.exitFullscreen();
    } else if (document.mozCancelFullScreen) {
      document.mozCancelFullScreen();
    } else if (document.webkitExitFullscreen) {
      document.webkitExitFullscreen();
    } else if (document.msExitFullscreen) {
      document.msExitFullscreen();
    }
    fullscreen = false;
  } else {
    if (elem.requestFullscreen) {
      elem.requestFullscreen();
    } else if (elem.mozRequestFullScreen) {
      elem.mozRequestFullScreen();
    } else if (elem.webkitRequestFullscreen) {
      elem.webkitRequestFullscreen();
    } else if (elem.msRequestFullscreen) {
      elem.msRequestFullscreen();
    }
    fullscreen = true;
  }
}
</script>
<style>
body {
  color: #000;
  background-color: white;
  font-family: Verdana, Helvetica, sans-serif;
  font-size: 16pt;
  margin: 8mm;
}
h1, h2, h3, h4, h5, h6 {
  color: black;
  background-color: inherit;
  clear: both;
  font-weight: bold;
  margin-top: 5mm;
}
a {
  color: #000;
  text-decoration: none;
  background-color: transparent;
}
a:hover, a:active, a.icon:hover, a.icon:active {  color: #666;  }
a.icon { font-size: 32pt; }
table.cover {
  margin-bottom: 8mm;
  width: 360px;
}
table.cover td {
  vertical-align: middle;
  text-align: center;
}
img {
  width: 360px;
  border-style: solid;
  border-color: black;
  border-width: 1px;
}
div.left, div.right {
  width: 60px;
  height: 60px;
  margin-bottom: 20px;
  text-align: center;
}
div.left { float: left; }
div.right { float: right; }
</style>"

HEAD2="</head><body>"
TAIL="</body></html>"

echo "$HEAD1" > index.html
echo "<title>Audix</title>" >> index.html
echo "$HEAD2" >> index.html
echo "<div class=\"right\"><a class=\"icon\" onclick=\"toggleFullScreen()\" href=\"#\">&#x26F6;</a></div>" >> index.html

IFS=$'\n'
C=0
for D in $(ls -1v . | egrep -v "\.[a-z]*$"); do
  C=$((C+1))
  DP=$(echo "$D" | sed 's/ /%20/g')
  echo "<table class=\"cover\" id=\"album$C\">" >> index.html
  echo "<tr><td><a href=\"$DP/index.html\"><img src=\"$DP/cover.jpg\" alt=\"cover\"></a></td></tr>" >> index.html
  echo "<tr><td><a href=\"$DP/index.html\">$D</a></td></tr>" >> index.html
  echo "</table>" >> index.html
  echo "$HEAD1" > $D/index.html
  echo "<title>$D</title>" >> $D/index.html
  echo "$HEAD2" >> $D/index.html
  echo "<div class=\"left\"><a class=\"icon\" href=\"../index.html#album$C\">&#x2BC7;</a></div>" >> $D/index.html
  echo "<div class=\"right\"><a class=\"icon\" onclick=\"toggleFullScreen()\" href=\"#\">&#x26F6;</a></div>" >> $D/index.html
  echo "<h1>$D</h1>" >> $D/index.html
  echo "<img src=\"cover.jpg\" alt=\"cover\">" >> $D/index.html
  echo "<table>" >> $D/index.html
  for A in $(ls -1v $D | egrep "\.(wav|ogg|m4a|mp3)$"); do
    AX=${A%.*}
    AP=$(echo "$A" | sed 's/ /%20/g')
    echo "<tr><td><audio controls><source src=\"$AP\"></audio></td><td>$AX</td></tr>" >> $D/index.html
  done
  echo "</table>" >> $D/index.html
  echo "$TAIL" >> $D/index.html
done

echo "$TAIL" >> index.html
